#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

rocker --x11 \
    --nvidia \
    --name=${DOCKER_CONTAINER_NAME} \
    --network=${ROS_NETWORK} \
    --volume ${PROJECT_ROOT}/shared:/shared \
    --volume ${PROJECT_ROOT}/src:/catkin_ws/src \
    --env TURTLEBOT3_MODEL=burger \
    -- ${DOCKER_IMAGE_NAME} /autostart.sh roscore
